apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.spec.serviceaccountname }}
      containers:
        - name: {{ .Values.spec.containers.name}}
          image: {{ .Values.spec.containers.image}}
          ports:
          - containerPort: {{ .Values.spec.containers.containerport }}
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:5050"]
          env:
          - name: PORT
            value: {{ .Values.spec.containers.env.port}}
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: {{ .Values.spec.containers.env.productcatalog}}
          - name: SHIPPING_SERVICE_ADDR
            value: {{ .Values.spec.containers.env.shippingservice}}
          - name: PAYMENT_SERVICE_ADDR
            value: {{ .Values.spec.containers.env.paymentservice}}
          - name: EMAIL_SERVICE_ADDR
            value: {{ .Values.spec.containers.env.emailservice}}
          - name: CURRENCY_SERVICE_ADDR
            value: {{ .Values.spec.containers.env.currencyservice}}
          - name: CART_SERVICE_ADDR
            value: {{ .Values.spec.containers.env.cartservice}}
          # - name: DISABLE_STATS
          #   value: "1"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: {{ .Values.spec.containers.resources.requestscpu }}
              memory: {{ .Values.spec.containers.resources.requestsmemory}}
            limits:
              cpu: {{ .Values.spec.containers.resources.limitscpu }}
              memory: {{ .Values.spec.containers.resources.limitsmemory }}