apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: cartservice
spec:
  resources:
    - name: repo
      type: git
  tasks:
  - name: cartservice
    taskRef:
      name: cartservice
    resources:
        inputs:
          - name: repo
            resource: repo