apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.serviceaccountname }}
      terminationGracePeriodSeconds: {{ .Values.terminationgraceperiodseconds }}
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: {{ .Values.containers.containerport }}
        env:
        - name: PORT
          value: {{ .Values.containers.env.value }}
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
        resources:
          requests:
            cpu: {{ .Values.containers.resources.requestscpu }}
            memory: {{ .Values.containers.resources.requestsmemory }}
          limits:
            cpu: {{ .Values.containers.resources.limitscpu }}
            memory: {{ .Values.containers.resources.limitsmemory }}