apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
  - name: {{ .Values.service.ports.name }}
    port: {{ .Values.service.ports.port }}
    targetPort: {{ .Values.service.ports.targetport }}