apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.serviceaccountname }}
      terminationGracePeriodSeconds: {{ .Values.terminationgraceperiodseconds }}
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: {{ .Values.containers.port}}
        env:
        - name: PORT
          value: {{ .Values.containers.env.value }}
        # - name: DISABLE_STATS
        #   value: "1"
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: DISABLE_PROFILER
        #   value: "1"
        # - name: JAEGER_SERVICE_ADDR
        #   value: "jaeger-collector:14268"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:3550"]
        resources:
          requests:
            cpu: {{ .Values.containers.resources.requestscpu}}
            memory: {{ .Values.containers.resources.requestsmemory}}
          limits:
            cpu: {{ .Values.containers.resources.limitscpu}}
            memory: {{ .Values.containers.resources.limitsmemory}}