apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: adservice
spec:
  pipelineRef:
    name: adservice
  resources:
    - name: repo
      resourceRef:
        name: helm-chart-demo-resources

  serviceAccountName: pipeline-account