apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emailservice
  namespace: demo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  project: default
  source:
    path: emailservice/
    repoURL: https://github.com/MaksimBars/helm-chart-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true