apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    path: frontend
    helm:
      values: |
        pushgateway:
          enabled: false
    repoURL: https://github.com/MaksimBars/helm-chart-demo.git
  syncPolicy:
    automated:
      prune: true
      selfHeal: true