apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loadgenerator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: microservicedemo
  source:
    path: loadgenerator/
    repoURL: https://github.com/MaksimBars/helm-chart-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true