apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: frontend
spec:
  resources:
    - name: repo
      type: git
  tasks:
  - name: frontend
    taskRef:
      name: frontend
    resources:
        inputs:
          - name: repo
            resource: repo