apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.serviceaccountname }}
      terminationGracePeriodSeconds: {{ .Values.terminationgraceperiodseconds }}
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        ports:
        - name: {{ .Values.containers.ports.name }}
          containerPort: {{ .Values.containers.ports.containerport }}
        env:
        - name: PORT
          value: {{ .Values.containers.env.value }}
        # - name: DISABLE_TRACING
        #   value: "1"
        # - name: DISABLE_PROFILER
        #   value: "1"
        # - name: DISABLE_DEBUGGER
        #   value: "1"
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7000"]
        resources:
          requests:
            cpu: {{ .Values.containers.resources.requestscpu }}
            memory: {{ .Values.containers.resources.requestsmemory }}
          limits:
            cpu: {{ .Values.containers.resources.limitscpu }}
            memory: {{ .Values.containers.resources.limitsmemory }}