apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.serviceaccountname }}
      terminationGracePeriodSeconds: {{ .Values.terminationgraceperiodseconds }}
      containers:
      - name: {{ .Values.containers.name }}
        image: {{ .Values.containers.image }}
        ports:
        - containerPort: {{ .Values.containers.port }}
        env:
        - name: REDIS_ADDR
          value: {{ .Values.containers.env.value }}
        resources:
          requests:
            cpu: {{ .Values.containers.resources.requestscpu }}
            memory: {{ .Values.containers.resources.requestsmemory }}
          limits:
            cpu: {{ .Values.containers.resources.limitscpu }}
            memory: {{ .Values.containers.resources.limitsmemory }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.containers.readinessprobe.delayseconds }}
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]
        livenessProbe:
          initialDelaySeconds: {{ .Values.containers.livenessprobe.delayseconds }}
          periodSeconds: {{ .Values.containers.livenessprobe.periodseconds }}
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:7070", "-rpc-timeout=5s"]