apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: currencyservice
spec:
  resources:
    - name: repo
      type: git
  tasks:
  - name: currencyservice
    taskRef:
      name: currencyservice
    resources:
        inputs:
          - name: repo
            resource: repo