apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: loadgenerator
spec:
  resources:
    - name: repo
      type: git
  tasks:
  - name: loadgenerator
    taskRef:
      name: loadgenerator
    resources:
        inputs:
          - name: repo
            resource: repo