apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: productcatalogservice
spec:
  resources:
    - name: repo
      type: git
  tasks:
  - name: productcatalogservice
    taskRef:
      name: productcatalogservice
    resources:
        inputs:
          - name: repo
            resource: repo