apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: {{ .Values.annotations }}
    spec:
      serviceAccountName: {{ .Values.serviceaccountname }}
      containers:
        - name: {{ .Values.containers.name }}
          image: {{ .Values.containers.image }}
          ports:
          - containerPort: {{ .Values.containers.containerport }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.containers.readinessprobe.delayseconds }}
            httpGet:
              path: {{ .Values.containers.readinessprobe.httpget.path }}
              port: {{ .Values.containers.readinessprobe.httpget.port }}
              httpHeaders:
              - name: {{ .Values.containers.readinessprobe.httpget.httpheaders.name }}
                value: {{ .Values.containers.readinessprobe.httpget.httpheaders.value }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.containers.livenessprobe.delayseconds}}
            httpGet:
              path: {{ .Values.containers.livenessprobe.httpget.path }}
              port: {{ .Values.containers.livenessprobe.httpget.port }}
              httpHeaders:
              - name: {{ .Values.containers.livenessprobe.httpget.httpheaders.name }}
                value: {{ .Values.containers.livenessprobe.httpget.httpheaders.value }}
          env:
          - name: PORT
            value: {{ .Values.containers.env.portvalue }}
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: {{ .Values.containers.env.productcatalogservice }}
          - name: CURRENCY_SERVICE_ADDR
            value: {{ .Values.containers.env.currencyservice }}
          - name: CART_SERVICE_ADDR
            value: {{ .Values.containers.env.cartservice }}
          - name: RECOMMENDATION_SERVICE_ADDR
            value: {{ .Values.containers.env.recommendationservice }}
          - name: SHIPPING_SERVICE_ADDR
            value: {{ .Values.containers.env.shippingservice }}
          - name: CHECKOUT_SERVICE_ADDR
            value: {{ .Values.containers.env.checkoutservice }}
          - name: AD_SERVICE_ADDR
            value: {{ .Values.containers.env.adservice }}
          # # ENV_PLATFORM: One of: local, gcp, aws, azure, onprem, alibaba
          # # When not set, defaults to "local" unless running in GKE, otherwies auto-sets to gcp 
          # - name: ENV_PLATFORM 
          #   value: "aws"
          # - name: DISABLE_TRACING
          #   value: "1"
          # - name: DISABLE_PROFILER
          #   value: "1"
          # - name: JAEGER_SERVICE_ADDR
          #   value: "jaeger-collector:14268"
          resources:
            requests:
              cpu: {{ .Values.containers.resources.requestscpu }}
              memory: {{ .Values.containers.resources.requestsmemory }}
            limits:
              cpu: {{ .Values.containers.resources.limitscpu }}
              memory: {{ .Values.containers.resources.limitsmemory }}