apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.spec.type }}
  selector:
    app: {{ .Values.name }}
  ports:
  - name: {{ .Values.spec.ports.name }}
    port: {{ .Values.spec.ports.port }}
    targetPort: {{ .Values.spec.ports.targetport }}